name: ci

on:
  push:
    branches:
      - main
      - '!dependabot/**'

permissions:
  contents: read

jobs:
  approved:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Allow to run spec!"

  jest:
    name: node
    needs: [approved]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14', '16', '18']

    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn Dependencies
        run: yarn install --frozen-lockfile

      - name: Yarn Jest
        run: yarn test